# DSCI 430 - Fairness, Accountability, Transparency and Ethics (FATE) in Data Science

# Module 1 - Introduction and Ethical foundations 



### Assignment overview

This assignment is composed of four parts:
- **Part 1 - FATE fundamentals.** To start the assignment, we will review the concepts of Fairness, Accountability, Transparency, and Ethics in data science, and use them to analyze some real scenarios.
- **Part 2 - The Black Mirror Writers' Room.** In this portion of the exercise, you will brainstorm near future technology and its possible drawbacks, and illustrate them in a futuristic cautionary tale. You will also be asked questions about ethical theories and how they apply to the scenario you have described. Credits: [Casey Fiesler - The Black Mirror Writers Room: The Case (and Caution) for Ethical Speculation in CS Education](https://medium.com/cuinfoscience/the-black-mirror-writers-room-the-case-and-caution-for-ethical-speculation-in-cs-education-5c81d05d2c67)
- **Part 3 - Python review.** As this course uses Python as the programming language for our exercises, a basic understanding of the fundamentals and the use of some libraries is necessary. This portion of the exercise will help you review useful Python syntax and/or fill the gap in your knowledge before tackling larger exercises. We recommend discussing with an instructor if you find this portion of the assignment too difficult to complete with a reasonable amount of effort.
- **Part 4 - Final thoughts.** Complete this section so that we can better understand how you completed the assignment and any issues you may have encountered.

For this assignment, it is possible to work in **groups of up to 2 students**. Read the instructions carefully, as they may assign tasks to specific students.

### Group members
Leave Student 2 blank if group has less than 2 members:
- Student 1: Christopher Chen
- Student 2: Renata Liu

### Learning Goals:

After completing this week's lecture and tutorial work, you will be able to:
1. Define ethics and describe what constitutes an ethical issue 
2. Explain the need for ethics in data science  
3. Identify common ethical issues in data science  
4. Describe common ethical frameworks and how they can be applied to data science applications 
5. Imagine scenarios in which current technology could be used in unethical ways 
6. Evaluate and make arguments around data science scenarios using ethical theories (e.g., Kantianism, utilitarianism, virtue ethics etc.)  
7. Compare and contrast different ethical theories and explain the case for and against each one as they apply to data science

# FATE fundamentals

## Warm up

Before jumping into the creative writing part, we should review the various elements of FATE in data science and make sure that they are clear:

| FATE element    | Definition |
| :-------- | :------- |
| **Fairness**  | The idea that every group or population that is affected by a technological application is being treated equally and not receiving a different outcome *solely because they belong to their group*.   |
| **Accountability** | In data science, accountability aims at setting up preventative or mitigation strategies to make owners, designers, or users of data science applications responsible for the consequences of their actions; identification and implementation of measures to reduce the potential negative impact of data science applications. |
| **Transparency** | The technical definition of transparency in data science refers to being able to understand why a technological application produced a specific outcome. This is also called *explainability*. Transparency can also refer to the demand of making the use of algorithms more transparent to the public, including informing the users about when they are used, where the data used was sourced from, and making algorithms available for auditing.|
| **Ethics** | Evaluation of whether or not a technology should be used based on the moral values of a group or society. Society may reject a technology because it is does not follow the principles of Fairness, Accountability or Transparency, but also for other reasons.|

### Question 1

Consider the following scenario:

In the country of Dataland, the police department uses an algorithm to assess the risk level of people reporting cases of domestic abuses and violence. Thanks to this algorithm, they can identify the most serious threats and intervene accordingly. The algorithm has had a positive impact, assessing cases with more accuracy and at greater scale than other prior strategies and allowing the police force to make an efficient use of their resources. However, it occasionally fails to correctly identify people at high risk of violence (*false negatives*), leaving them without the protection they need. It is also affected by other issues. For each issue outlined in this table, check whether it is a Fairness, Accountability or Transparency problem.

| Issue    | Fairness | Accountability | Transparency |
| :-------- | :------- | :------- | :------- |
| When the algorithm fails to identify a high-risk case and violence occurs, it is unclear if the police department should shoulder any responsibility. |        |     x   |        | 
| An analysis of the algorithm's results suggests that false negatives occur more frequently among victims with physical disabilities. |    x    |        |        | 
| The majority of people reporting domestic abuse are not aware that their cases are being evaluated by an algorithm, or do not know the score they received. |        |        |      x  | 
| The police department receives a recommendation for each case, but does not know which characteristic(s) of the case have resulted in the final evaluation. |        |        |    x    | 
| The algorithm was trained using past cases filed by the police department, but the people involved where not informed that their information was being used for this purpose. |        |        |   x     | 

### Question 2

Consider the issues outlined in the previous question, as well as the fact that the algorithm is the best system of appraisal available to the police forces so far for cases of domestic violence. Do you think that the use of this algorithm is *ethical*? Clearly state your thesis (opposed/favourable) and use one of the ethical perspectives listed in [this reading](https://www.scu.edu/ethics-in-technology-practice/ethical-lenses/) to support it (a summary is available in the table below).

![](ELsummary.png)

**ANSWER**

No, we do not think the use of the algorithm is ethical. 

By the Rights perspective, the central question about this algorithm is whether the people affected are being treated as autonomous, dignified individuals with the right to consent to decisions that affect them, or if they're simply being treated as a means to an end. Using this perspective, the algorithm is unethical because the people reporting domestic abuse are not informed that their case is being evaluated algorithmically, nor are they told the score they receive, which denies them any meaningful ability to understand, question, or contest a process that directly affects their safety.

The algorithm is also trained on past cases without informing the people involved that their personal data would be used, thus treating their information as a resource for institutional efficiency. The police department itself cannot explain how the score was obtained, meaning no one has a real path to understanding the outcome. Although the algorithm is the "best-performing option available", failing to respect the autonomy and dignity of the people it affects makes its use unethical.

**Note:** this case is fictional but inspired by a real algorithm, called VioGén, used in Spain to determine the risk level of victims of gender-based violence and assign protection measures. The algorithm has been recently going under severe scrutiny [(Read more).](https://eticas.ai/the-adversarial-audit-of-viogen-three-years-later/)

### Question 3

Given the fast pace at which new data science applications and AI technologies are developed, new use cases and scenarios pop up all the time. As practitioners and students of this course, it is important that you are able to find and analyze new scenarios independently.

For this exercise, you are asked to do the following:
- Browse reliable sources and find a new example of AI/data science application that you think needs to be analyzed further using our FATE lenses.
- Fill the table below, outlining how they are connected to the FATE elements. If an element is not connected, states so, and provide a brief explanation of why. For the Ethics element, a full argumentation using an ethical framework is not required - just describe how, in your view, the use of this technology could result in an ethical dilemma.

With a little research, you should be able to find a great number of scenarios fit for this exercise. Most of them will be appropriate for discussion, but make sure that they come from a verifiable and reliable source.

Good sources include:
- Communications from organizations in this domain, such as the [Communications of the ACM](https://cacm.acm.org/) or the [Center for AI and Digital Policy](https://www.caidp.org/).
- Reputable news outlets; these will typically include a link to the original source/study - include all relevant sources in your report.

Poor sources include:
- Social media posts, unless they cite a reliable source (in which case, just cite the latter)
- LLMs summaries - unfortunately, the LLMs tendency to [hallucinate](https://en.wikipedia.org/wiki/Hallucination_(artificial_intelligence)) when asked this kind of questions is quite high.

**Summary**

Flock Safety is a company that sells "license plate readers" to municipalities across the US. Their function is to install networks of cameras that can read license plates. The advertised functions are 
to keep communities safe, for example by helping police track criminal license plates. However, Flock has come under scrutiny and push back, as American citizens are not comfortable with the placement of cameras in public spaces.
**Sources**

- https://www.bbc.com/news/articles/cew9kz1kxpvo
- https://fortune.com/2026/06/03/why-are-ohio-city-workers-covering-flock-cameras-immigration-enforcement-data-sharing-policy-violations/
- https://www.npr.org/2026/02/17/nx-s1-5612825/flock-contracts-canceled-immigration-survillance-concerns
- https://immpolicytracking.org/policies/reported-ice-accessing-flock-automated-license-plate-reader-cameras-via-local-law-enforcement/
| FATE element    | Explanation | 
| :-------- | :------- | 
| Fairness |    *While the camera scans license plates equally, the treatment and tracking of targets identified are not known. It is very possible that the camera is tracking certain traits about targets.*    |       
| Accountability |    *As Flock only sets up the cameras, they do not have a responsibility to look over the uses of the data, which they send to other institutions (like police stations). If the data is misused, the consequences may lie with the perpetrator and not Flock.*    |        
| Transparency |   *This is the biggest issue with Flock Inc. The public does not know how the data is being used and shared, and Flock does not have a legal reason to be transparent.*    |        
| Ethics |    *This technology raises ethical questions about public surveillance, and we know that many people are uncomfortable with being watched in public, even if they are doing "nothing wrong". At the same time, there are also ethical questions about the right of private companies to have control over public surveillance, as we know that their objective is to maximize profit.*    |

# Black Mirror Writer's room

[Black Mirror](https://en.wikipedia.org/wiki/Black_Mirror) is a Netflix series centered around the use of advanced technology and its possible unexpected (sometimes catastrophic) consequences. In this exercise, you will come up with your very own Black Mirror episode (or at least a synopsis)! 

Now that you have acquired the necessary familiarity with some required knowledge and terminology, it is time to use your creativity!

**Step 1:** Brainstorm *one* near future technology based on a topic of your choice. It should be close enough that it seems like a plausible future. Describe it in the next cell.

*AI agents embedded into your brain (Neuralink x Chatgpt)*

**Step 2:** What are the potential social implications and/or ethical issues and/or regulatory challenges with this technology? Explain if and how they are connected to FATE (e.g. is it a Fairness issue? Or maybe a Transparency issue? It could be more than one option).

| FATE element    | Explanation | 
| :-------- | :------- | 
| Fairness |    *Certain people may have advantages in society by possessing a version of this technology.*    |       
| Accountability |        |        
| Transparency |    *We are not sure what the capabilities and functions of advanced brain interfaces are.*    |        
| Ethics |    *It may be perceived as inhumane to have an AI models in your brain, and it challenges spiritual thinking. Also, how much control will companies have over technology that interfaces with your brain?*    |

**Step 3:** Time for storytelling! Write the summary of a new Black Mirror episode based on the technology of your choice. Try covering all of the following:

- What do you think might be a cautionary tale related to this technology? 
- What fictional person in the future would best illustrate this caution? Provide a detailed description and tell us their story. Explain their background, their motivations, and their journey through your episode. Try to highlight what makes them the best character to carry your message.

As part of your submission, please update the episode thumbnail slide (from Module 1 slide deck) using information from your episode. Don't forget to add a picture! Then, share it with the rest of the class on [Canvas](https://canvas.ubc.ca/courses/178436/discussion_topics/2828247).

Bob is an ambitious, young software engineer, who is offered a high paying job at a large company. This company has a culture of high performance and has recently mandated its employees to install NeuralinkAI, a brain-chip that allows you to interface with an AI assistant in your head, for productivity's sake. Although Bob has some concerns, the prestige of the job draws him in to accept the offer. Shortly after starting, Bob finds that his outputs are magnitudes higher with NerualinkAI. He feels superhuman at work. But slowly, the difference between work and life starts getting blurry, and Bob finds himself working even when he doesn't want to.

**Step 4:** Let's take a step back, and imagine that you are (one of) an activist/legistlator/technology practitioner at the time the technology described in your episode is being developed and its use being discussed. Select *one* of the ethical perspectives listed in [this reading](https://www.scu.edu/ethics-in-technology-practice/ethical-lenses/), and use this perspective to argue against its deployment. Pay particular attention to the counter-arguments! People with interests in this technology will certainly argue against you, and you must anticipate and rebut their claims. Include at least 2 conter-arguments and how you would respond to them.

**Ethical perspective chosen:** 
Rights Perspective
**Argument:**
One part of Kant's categorical imperative states that actions towards humans should treat them as 'ends in themselves'. By installing a technology solely to make one more productive at work, one is allowing a company to treat themselves as a means to an ends. Additionally, we could say that allowing an interface with ones brain compromises ones dignity and autonomy. Your dignity is compromised because you are viewed as both a tool and a human, and valued as such. Ones autonomy is compromised because we are not sure to what degree ones free actions are ones own.

**First counter-argument (with rebuttal):**
It is a persons own choice to install this technology: there is no deception, therefore this technology is not treating someone as a means to an end. 

Rebuttal: deception is not necessary to treat one as a means to an end. One can argue that even though a person chooses to install a technology, they are not doing so out of true free will. Bob is under economic and social pressure to install NeuralinkAI. Additionally, Bob's productivity is not for himself but for his employer.
.
**Second counter-argument (with rebuttal):**
This technology strictly increases a person's capacity for work, such as computers and calculators. It is a logical industrial step for humankind, and hindering this technology would be hindering progress.

Rebuttal: A person could be coerced to use this technology for productivity sake. Additionally, a technology that implants into your brain has the potential to limit your autonomy.

**Step 5:** Finally, let's end on a more positive note and imagine a "Light Mirror" scenario, where the negative consequences of the technology you have described are averted and positive results are achieved in their stead. Try answering the following questions:

1. What kinds of solutions can be deployed in the immediate for addressing the harms of the technology you have described? What could we do to ensure that we don’t get to the negative consequences you imagined later in the future? 
2. Could you imagine a scenario where the technology you have described is used with positive consequences, given the appropriate safe guards?

*We should ensure that this technology is designed in such a way that a user has full control over the implant (make it removable or turn-offable in absolute). I do see that this technology would be great for reduced workload and information convenience, if users were in full control.*

### Sources
The Black Mirror Writers' Room exercises was designed by [Dr. Casey Fiesler](https://caseyfiesler.com/). Links to her work and publications:
- [The Black Mirror Writers Room: The Case (and Caution) for Ethical Speculation in CS Education](https://medium.com/cuinfoscience/the-black-mirror-writers-room-the-case-and-caution-for-ethical-speculation-in-cs-education-5c81d05d2c67)
- ["Run Wild a Little With Your Imagination": Ethical Speculation in Computing Education with Black Mirror](https://dl.acm.org/doi/abs/10.1145/3478431.3499308)

# Python Review

In this section of the assignment, we will review useful Python functions and libraries that will allow you to read and analyze data, as well as training simple Machine Learning models. 

## Section 1: Exploring datasets with Pandas

First, we will need a dataset to work on. Let's use a [weather type dataset](https://www.kaggle.com/datasets/nikhil7280/weather-type-classification), a good starting dataset (we will save more interesting cases for later!). Download this dataset from the link to use it for this exercise.

We also need to import the necessary library to read and manipulate our dataset, which is [Pandas](https://pandas.pydata.org/pandas-docs/stable/index.html). The imports are given to you. Next, use the `read_csv()` function to import the data in your workspace. The documentation for this function can be found [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

In [2]:
import pandas as pd

# YOUR ANSWER HERE
df = pd.read_csv("weather_classification_data.csv")
df.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy

Now, let's use the [`describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) function of the Pandas library to get an overview of the dataset, and answer the following questions (you can write your answers in this box):

- What is the maximum temperature recorded in the dataset? *109 C*
- What is the average wind speed? *9.83*

Note: some of the values you will see may appear unrealistic (such as incredibly high temperatures). The dataset is artificially generated and purposefully includes outliers to practice detection and handling, but it is not something we will worry about it this exercise - we are just interested in getting some practice with useful commands.

In [3]:
# YOUR ANSWER HERE
df.describe()

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
count,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000
mean,19.127576,68.710833,9.832197,53.644394,1005.827896,4.005758,5.462917
std,17.386327,20.194248,6.908704,31.946541,37.199589,3.856600,3.371499
min,-25.000000,20.000000,0.000000,0.000000,800.120000,0.000000,0.000000
25%,4.000000,57.000000,5.000000,19.000000,994.800000,1.000000,3.000000
50%,21.000000,70.000000,9.000000,58.000000,1007.650000,3.000000,5.000000
75%,31.000000,84.000000,13.500000,82.000000,1016.772500,7.000000,7.500000
max,109.000000,109.000000,48.500000,109.000000,1199.210000,14.000000,20.000000

The `describe()` function is helpful, but it does not answer all the questions we may have. For example, we did not get any idea about the class distribution in our dataset, that is, how many samples we have for each of the four classes (Rainy, Cloudy, Sunny, Snowy). Can you write a line of code to answer this question?

In [4]:
# YOUR ANSWER HERE
df["Weather Type"].value_counts()

Weather Type
Rainy     3300
Cloudy    3300
Sunny     3300
Snowy     3300
Name: count, dtype: int64

Thanks to `describe()`, we know that the minimum temperature recorded is -25 C, but we have no idea which sample it belongs to. Can you write a line of code to find the sample number and also the Weather Type associated to it?

In [5]:
# YOUR ANSWER HERE
df.loc[df["Temperature"].idxmin()]

Temperature                -25.0
Humidity                     105
Wind Speed                  29.0
Precipitation (%)          106.0
Cloud Cover             overcast
Atmospheric Pressure      980.86
UV Index                       1
Season                    Winter
Visibility (km)              2.5
Location                mountain
Weather Type               Snowy
Name: 4609, dtype: object

Again thanks to `describe()`, we know that 25% of the samples in the dataset have a recorded Precipitation higher that 82 (you can verify this in the output table), but how many of these are Snowy? Answer this question in 1 line of code.

In [6]:
# YOUR ANSWER HERE
((df["Precipitation (%)"] > 82) & (df["Weather Type"] == "Snowy")).sum()

np.int64(1243)

Finally, sometimes we may be interested in sorting the dataframe by the values in a column. In this cell, sort the dataframe by humidity in descending order, and check the results by printing the first 5 rows.

In [7]:
# YOUR ANSWER HERE
df.sort_values("Humidity", ascending=False).head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
1303,29.0,109,21.0,93.0,partly cloudy,1018.98,9,Winter,7.5,inland,Cloudy
8716,16.0,109,27.0,102.0,overcast,1007.30,1,Winter,11.5,inland,Cloudy
9707,51.0,109,17.0,98.0,overcast,994.03,8,Spring,5.5,coastal,Rainy
2812,16.0,109,39.0,87.0,partly cloudy,1011.38,11,Spring,2.0,inland,Rainy
12566,4.0,109,16.0,93.0,overcast,988.15,12,Winter,3.5,inland,Snowy

As last step of this section, save the sorted dataframe in a new csv file called "weather_data_by_humidity.csv"

In [12]:
# YOUR ANSWER HERE
df.sort_values("Humidity", ascending=False).to_csv("weather_data_by_humidity.csv", index=False)

## Section 2: Training ML models with Scikit-learn

We are now interested in creating a model to predict the weather type based on the features available. Let's see how to do that using the python library [Scikit-learn](https://scikit-learn.org/stable/), while reviewing some important concepts about training and evaluating models. Simply run the cells below to see the output and answer the related questions.

First, we need to split our data set into training and testing set. The next cell shows how to do that. We will also separate the Weather Type column (target) from the other columns (features)

In [14]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.2, random_state=123)  # 80%-20% train test split on df

#X_train is train_df with the "Weather Type" column removed (training input features)
#y_train is just the "Weather Type" column from train_df (outputs model will try to predict)
X_train, y_train = train_df.drop(columns=["Weather Type"]), train_df["Weather Type"]

#similar to x, y train above but with testing sets
X_test, y_test = test_df.drop(columns=["Weather Type"]), test_df["Weather Type"]

X_train.head()  # quick visual check on X_train, the features dataframe

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location
12987,26.0,45,3.5,10.0,clear,1011.01,7,Autumn,5.0,inland
905,29.0,71,21.0,86.0,partly cloudy,1013.77,12,Winter,6.5,inland
5590,38.0,63,5.5,11.0,clear,1013.87,11,Spring,7.5,mountain
7269,17.0,66,18.0,63.0,partly cloudy,992.22,1,Winter,2.5,inland
1417,32.0,39,7.5,3.0,clear,1021.43,9,Autumn,5.5,inland

**Question for you:** creating a testing set is very important when training a model. **Why? How is it used? What would happen if we did not do this very important step?**

*Why testing set is important*

Creating a testing set is very important when training a model because the whole point of training a machine learning model is to make good predictions on *new, unseen* data. If a model is evaluated on how well it performs with a data set that was used to train it, the model will be overly accurate because it has seen the data before. By putting aside a test set, it provides an unbiased way to estimate how well the model will actually perform once it's deployed in the real world on samples it has never encountered before.

*How it is used*

(1) Train the model (ie. let it learn the patterns) only on X_train/y_train

(2) Use the trained model to make predictions on X_test (which it has never seen)

(3) Compare those predictions to the true labels y_test to compute performance metrics (accuracy, precision, recall, etc.).

*What would happen if the data set was not split into testing and training*

If the model is trained and evaluated on the same data, it would be "overfit" to the data because instead of learning the true underlying patterns, the model would "memorize" the training data, including noise and outliers. If the model is then evaluated using the data it memorized, it would create the illusion that the model performs amazingly well, when it reality it would not generalize well on new data samples.

As you can see, the dataset includes categorical features. Most classifiers require categorical features to be transformed before they can be used for training and prediction. The code below uses [One Hot Encoding](https://www.geeksforgeeks.org/ml-one-hot-encoding/) to convert the categorical features Cloud Cover, Season and Location, while leaving the numberical features unchanged.

This is a simple example of data preprocessing. Preprocessing can be more extensive (for example, including [scaling of numerical features](https://www.geeksforgeeks.org/ml-feature-scaling-part-2/)), but we are only interested in an overview of the fundamentals, so we will just apply One Hot Encoding to make the data usable.

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer

passthrough = ['Temperature', 'Humidity', 'Wind Speed', 'Precipitation (%)', 
               'Atmospheric Pressure', 'UV Index', 'Visibility (km)']
categorical = ['Cloud Cover', 'Season', 'Location']


ct = make_column_transformer(
    (OneHotEncoder(), categorical),  # OHE on categorical features
    ("passthrough", passthrough),  # no transformations on the numberical features
)

# Fit the encoder on the training data and transform
train_encoded = ct.fit_transform(X_train)

# Transform the test data
test_encoded = ct.transform(X_test)

# Convert the encoded data back to DataFrame for better readability

column_names = (
    ct.named_transformers_["onehotencoder"].get_feature_names_out().tolist() + passthrough
)

X_train_encoded = pd.DataFrame(train_encoded, columns=column_names)
X_test_encoded = pd.DataFrame(test_encoded, columns=column_names)

In [16]:
# Run this cell to see what the encoded data set looks like

X_train_encoded

,Cloud Cover_clear,Cloud Cover_cloudy,Cloud Cover_overcast,Cloud Cover_partly cloudy,Season_Autumn,Season_Spring,Season_Summer,Season_Winter,Location_coastal,Location_inland,Location_mountain,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,26.0,45.0,3.5,10.0,1011.01,7.0,5.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,29.0,71.0,21.0,86.0,1013.77,12.0,6.5
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,38.0,63.0,5.5,11.0,1013.87,11.0,7.5
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,17.0,66.0,18.0,63.0,992.22,1.0,2.5
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,32.0,39.0,7.5,3.0,1021.43,9.0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10555,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-19.0,27.0,5.5,66.0,929.72,9.0,14.5
10556,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,27.0,63.0,8.0,73.0,1016.64,2.0,1.0
10557,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,25.0,23.0,4.5,13.0,1014.45,11.0,6.5
10558,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,38.0,39.0,9.0,10.0,1018.10,10.0,7.0
10559,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,11.0,61.0,9.5,41.0,1008.30,3.0,6.5

**Question for you:** It appears that we applied the same One Hot Encoding transformation to both training and test set. Why did we bother doing this operation on the separate sets? Could have we just transformed the original dataframe `df`, and then split it in training and test set?

*ANSWER*

No, we could not have just transformed the original dataframe then split it into training a testing sets because doing so may have created data leakage. No, we could not have just transformed the original dataframe then split it into training and testing sets because doing so may have created data leakage. If we had performed the encoding all at once, the OneHotEncoder would have been fit on the entire dataset, including the test set. This means the encoder's knowledge of which categories exist for each categorical feature would already reflect information from the test set, even though the test set is meant to represent completely unseen, future data that the model should have no access to during training.

In general, it is best practice to perform any sort of preprocessing separately on each of the training and testing data sets to simulate how the model will be used in the real world (since the preprocessing of the new data will happen separately from the training data).

There are many classifiers we can choose from. We will use [Decision Trees](https://scikit-learn.org/stable/modules/svm.html) to start. Decision trees are very simple classification algorithms, although they have typically mediocre performance on complex classification problems.

A certain level of familiarity with Decision Trees is expected in this course. You may want to review the material from your previous courses, or this [introduction](https://www.youtube.com/watch?v=ZVR2Way4nwQ).

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt


model = DecisionTreeClassifier() # Create a decision tree
model.fit(X_train_encoded, y_train) # Fit a decision tree

DecisionTreeClassifier()

Now that we have the tree, we want to see how well it performs. Let's first check the accuracy on the training set:

In [18]:
model.score(X_train_encoded, y_train) # Score the decision tree

1.0

**100% accuracy!!!**

...

This sounds too good to be true... let's check the test set to see how well the trees perform on unseen samples:

In [19]:
model.score(X_test_encoded, y_test) # Score the decision tree on test set

0.9090909090909091

Accuracy dropped significantly when we moved to unseen samples!

This is because the Decision Tree, if left unsupervised, is very prone to **overfitting**. 

**Question for you:** what does it mean for a model to overfit?

*ANSWER*

The model overfits when it learns the training data too well, including its noise and random fluctuations, rather than learning the actual underlying patterns that generalize to new data. An overfit model typically has very high accuracy/very low error on the training set, but performs significantly worse on the test set/any unseen data.

To prevent a model from overfitting, we tune its **hyperparameters.** Hyperparameters are like knobs that we can use to regulate the way a model learn. 

Some hyperparameters for the scikit-learn DecisionTreeClassifier include:
- max_depth: the maximum distance between the root node and a leaf node
- min_samples_split: the minimum number of samples required to split an internal node
- min_samples_leaf; the minimum number of samples required to be at a leaf node

You can look up other hyperparameters and their default values in the DecisionTreeClassifier [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier). By default, the maximum depth value is set to *None*, that is, the tree is free to grow until it has parfectly classified all samples. As we have seen, this results in perfect accuracy on the training set, but much lower accuracy on unseen samples. 

Run the cell below to see the depth of our overfitted tree:

In [20]:
model.get_depth()

19

If we could find the right depth for our tree, we could reduce the problem of overfitting.

**Question for you:** what would happen if we reduce the depth of the tree *too much*? What do you expect the accuracy on training and test set to look like in this case?

*ANSWER*

If we reduce the depth of the tree too much, the model will be underfitted. This means that the model is too simple to represent the true complexity of the problem. A model that is underfitted will have low accuracy on both the training and test sets. 

*A NOTE ABOUT BIAS + VARIANCE*
Bias = error introduced by a model being too simple; high bias = underfit
Variance = model's sensitivity to noise; high variance = overfit

Hyperparameter tuning is typically done on a **validation set.** A validation set is a set of samples not used for training, like the test set, but unlike the test set, we are allowed to use this multiple times as we look for the best hyperparameter values.

Because our data set is rather small, it is not great to take more samples from the training set to create a validation set, because:
- We would have fewer samples (less information) to train our model
- The validation set would also be small, and result in a highly variable accuracy measure (meaning if we run the experiment again changing the samples in each set, we will likely get very different results)

There is a method that we can use to eliminate both problems, called ***k*-fold cross-validation.** Cross-validation iteratively separates training and validation set (*k* times), so we get multiple measures of accuracy on the validation sets, which can be averaged for a more stable result. A good understanding of how cross-validation works is important for any data scientist. I encourage you to review cross-validation from previous courses, or this [introduction video](https://www.youtube.com/watch?v=4cv8VYonepA) (courtesy of Dr. Kolhatkar).

Scikit-learn has a great method that we can use to perform cross-validation and find the best hyperparameters for a model at the same time, called [GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV). Let's use it to find the best depth for our Decision Tree:

In [21]:
from sklearn.model_selection import GridSearchCV
import numpy as np  # to create the array of values for depth

param_grid = {
    "max_depth": np.arange(1, 20, 1)  # testing all depths from 1 to 19
}

grid_search = GridSearchCV(
    model, param_grid, cv=10, n_jobs=-1, return_train_score=True   # 10-fold cross-validation for all possible 
                                                                   # depths
)
grid_search.fit(X_train_encoded, y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])},
             return_train_score=True)

In [22]:
grid_search.best_score_

np.float64(0.9105113636363636)

In [23]:
grid_search.best_params_

{'max_depth': np.int64(9)}

**Complete the sentence (replace --?--):** Among all possible trees, GridSearchCV picked a tree of depth **9**, with an average validation accuracy of **91.05%**.

The accuracy on the training set is no longer 100%, but we expect this tree to perform better on unseen samples. Let's try it on our test set:

In [24]:
best_tree = grid_search.best_estimator_

best_tree.score(X_test_encoded, y_test) # Score the decision tree on test set

0.9196969696969697

The accuracy is similar to when the model was overfitting, but hyperparameter tuning brought us 2 advantages:
- We had a more realistic expectation of what our accuracy was going to be (closer to 91%, not 100%)
- We simplified the model and reduced its depth. This makes the model faster and easier to visualize.

**Question for you:** on what samples (or portion of samples) of `X_train_encoded` was the final model (`best_tree`) trained on?

*ANSWER*

The model was trained on all samples of `X_train_encoded`.

The model can now be used to get predictions for unseen samples. For example:

In [25]:
random_sample = X_test_encoded.sample(n=1, random_state=42)

random_sample

,Cloud Cover_clear,Cloud Cover_cloudy,Cloud Cover_overcast,Cloud Cover_partly cloudy,Season_Autumn,Season_Spring,Season_Summer,Season_Winter,Location_coastal,Location_inland,Location_mountain,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
2005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,33.0,67.0,5.5,5.0,1015.42,10.0,8.0

In [26]:
best_tree.predict(random_sample)

array(['Sunny'], dtype=object)

# Final thoughts

1) If you have completed this assignment in a group, please write a detailed description of how you divided the work and how you helped each other completing it:

2) Have you used ChatGPT or a similar Large Language Model (LLM) to complete this homework? Please describe how you used the tool. **We will never deduct points for using LLMs for completing homework assignments,** but this helps us understand how you are using the tool and advise you in case we believe you are using it incorrectly.

3) Have you struggled with some parts (or all) of this homework? Do you have pending questions you would like to ask? Write them down here!